opiproject/opi-nvidia-bridge

frontend.go, frontend_test.go
- tests: implement TestFrontEnd_ListNVMeSubsystem
- move TestFrontEnd_DeleteNVMeSubsystem to be last
- tests: implement TestFrontEnd_GetNVMeSubsystem
=> tests: implement TestFrontEnd_GetNVMeSubsystem and TestFrontEnd_ListNVMeSubsystem

frontend.go, frontend_test.go, spdk.go
- tests: support array of spdk commands
- tests: use rpcID instead of hard-coded
- Fix FirmwareRevision tbd
=> Fix FirmwareRevision tbd

frontend.go, frontend_test.go
=> tests: implement TestFrontEnd_UpdateNVMeController and TestFrontEnd_NVMeControllerStats

frontend.go, frontend_test.go
=> tests: implement TestFrontEnd_CreateNVMeController

frontend_test.go
=> tests: implement TestFrontEnd_ListNVMeControllers

frontend.go, frontend_test.go
=> tests: implement TestFrontEnd_GetNVMeController

frontend.go, frontend_test.go
=> tests: implement TestFrontEnd_DeleteNVMeController

frontend.go, frontend_test.go
=> tests: implement TestFrontEnd UpdateNVMeNamespace and CreateNVMeNamespace

frontend_test.go
=> tests: implement TestFrontEnd_ListNVMeNamespaces

frontend_test.go
=> tests: implement TestFrontEnd_NVMeNamespaceStats

.github/workflows/docker-publish.yml, frontend.go, frontend_test.go
=> Slight refactor

.github/workflows/docker-publish.yml, docker-compose.yml, frontend.go, frontend_test.go
=> test docker compose in CI

.gitignore, frontend_test.go
Signed-off-by: patrick-alessi <patrick.alessi@dell.com>
=> Test refactor

.golangci.yml, frontend.go, spdk.go
=> Add linter rules and fix linter errors

README.md, docker-compose.yml
=> Fix client image

Dockerfile, README.md, cmd/main.go, pkg/frontend/frontend.go, pkg/frontend/frontend_test.go, pkg/frontend/spdk.go, pkg/frontend/spdk_test.go
=> go: don't use plugins anymore

pkg/frontend/frontend.go, pkg/frontend/frontend_test.go, pkg/models/spdk.go
=> Split to a new models package

pkg/frontend/frontend_test.go
=> Remove code dup

pkg/frontend/frontend_test.go
=> Add missing listener

pkg/frontend/frontend.go, pkg/models/spdk.go
=> re-use GetVersionResult

cmd/main.go, pkg/frontend/frontend.go, pkg/frontend/frontend_test.go
=> Avoid using global variables for NVMe parameters

pkg/frontend/virtio.go
=> VirtioBlk: start using nvidia specific calls

pkg/frontend/nvme.go, pkg/frontend/virtio.go, pkg/frontend/virtio_test.go, pkg/models/spdk.go
=> VirtioBlk use correct structs

pkg/frontend/virtio.go
=> Fix return value from list/get

pkg/frontend/virtio.go, pkg/frontend/virtio_test.go
=> ci: add TestFrontEnd_UpdateVirtioBlk

pkg/frontend/virtio_test.go
=> ci: add TestFrontEnd_DeleteVirtioBlk

pkg/frontend/virtio.go, pkg/frontend/virtio_test.go
=> ci: add TestFrontEnd_ListVirtioBlks

pkg/frontend/virtio_test.go
=> ci: add TestFrontEnd_GetVirtioBlk

pkg/frontend/virtio_test.go
=> ci: add TestFrontEnd_VirtioBlkStats

pkg/frontend/frontend.go, pkg/frontend/frontend_test.go, pkg/frontend/virtio.go, pkg/frontend/virtio_test.go
=> virtio: save controllers in global var

pkg/frontend/nvme.go, pkg/frontend/virtio.go
=> idempotency: delete should not fail if already deleted

pkg/frontend/nvme.go, pkg/frontend/virtio.go
=> codes.InvalidArgument when PageSize < 0

pkg/frontend/nvme_test.go, pkg/frontend/virtio_test.go
=> tests: pagination negative

pkg/frontend/nvme_test.go, pkg/frontend/virtio_test.go
=> tests: delete AllowMissing

pkg/frontend/nvme.go, pkg/frontend/nvme_test.go, pkg/frontend/virtio.go, pkg/frontend/virtio_test.go
=> List: respect `page_size`

pkg/frontend/nvme_test.go, pkg/frontend/virtio_test.go
=> tests: []struct -> map[string]struct

pkg/frontend/nvme_test.go, pkg/frontend/virtio_test.go
- tests: create if already exists
- tests: reflect.DeepEqual -> proto.Marshal
=> tests: create if already exists

pkg/frontend/nvme_test.go
=> test: error spdk_get_version

pkg/frontend/nvme.go, pkg/frontend/nvme_test.go, pkg/frontend/virtio.go, pkg/frontend/virtio_test.go
tests: add unit testing for those functions above
=> List: respect PageSize and PageToken

pkg/frontend/nvme.go, pkg/frontend/virtio.go, pkg/frontend/virtio_test.go
=> list: sort all results before returning them

pkg/frontend/nvme.go, pkg/frontend/nvme_test.go, pkg/frontend/virtio.go, pkg/frontend/virtio_test.go
=> create: use {resource}_id field if provided by user

pkg/frontend/nvme.go
=> nvme: check input parameters validity

pkg/frontend/nvme.go, pkg/frontend/virtio.go
=> Use resourceID in Create* calls.

pkg/frontend/nvme.go, pkg/frontend/virtio.go
=> {resource}_id: call ValidateUserSettable

pkg/frontend/nvme.go, pkg/frontend/virtio.go
=> Update*: call fieldmask.Validate

pkg/frontend/nvme_test.go
=> tests: test invald {resource}_id

pkg/frontend/nvme.go
Fixes opiproject/opi-spdk-bridge#441
=> prevent creation of nvme subsystem with same NQN

go.mod, go.sum, pkg/frontend/frontend_test.go, pkg/frontend/nvme_controller_test.go, pkg/frontend/nvme_namespace_test.go, pkg/frontend/nvme_subsystem_test.go, pkg/frontend/virtio_test.go
see https://github.com/opiproject/opi-spdk-bridge/issues/516
=> Test remove start spdk argument

pkg/frontend/nvme_controller_test.go, pkg/frontend/nvme_namespace_test.go, pkg/frontend/nvme_subsystem_test.go, pkg/frontend/virtio.go, pkg/frontend/virtio_test.go
No tests for Update and Stats calls since they do not have required fields yet
=> Test required fields

README.md, docker-compose.yml
see https://github.com/opiproject/godpu/pull/260
=> fix(godpu): new commands introduced

pkg/frontend/frontend_test.go, pkg/frontend/nvme_controller_test.go, pkg/frontend/nvme_namespace_test.go, pkg/frontend/nvme_subsystem_test.go, pkg/frontend/virtio_test.go
https://github.com/opiproject/opi-spdk-bridge/issues/443
=> test: check global test objects not changed

cmd/main.go, go.mod, go.sum
=> feat: add TLS option for gRPC connection

pkg/frontend/nvme_controller.go, pkg/frontend/nvme_controller_validate.go, pkg/frontend/nvme_namespace.go, pkg/frontend/nvme_namespace_validate.go, pkg/frontend/nvme_subsystem.go, pkg/frontend/nvme_subsystem_validate.go, pkg/frontend/virtio.go, pkg/frontend/virtio_test.go, pkg/frontend/virtio_validate.go
=> refactor: split validate logic to a new file

pkg/frontend/nvme_subsystem_test.go
=> test(nvme): check nqn, model and serial

.github/workflows/codeql.yml, .github/workflows/commitlint.yml, .github/workflows/docker-publish.yml, .github/workflows/go.yml, .github/workflows/linters.yml, .github/workflows/release-please.yml, .github/workflows/scorecard.yml, .github/workflows/update-copyright-years-in-license-file.yml
=> ci: move workflows to new repo

pkg/frontend/frontend_test.go, pkg/frontend/nvme_controller_test.go, pkg/frontend/nvme_namespace_test.go, pkg/frontend/nvme_subsystem_test.go
=> test: introduce withstatus objects

go.mod, go.sum, pkg/frontend/frontend_test.go, pkg/frontend/nvme_namespace.go, pkg/frontend/nvme_namespace_test.go
=> refactor(frontend): adjust to changed states in nvme api
